// <auto-generated />
namespace ERP.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_field__voucherNumber_Notes_in_VoucherDetail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_field__voucherNumber_Notes_in_VoucherDetail));
        
        string IMigrationMetadata.Id
        {
            get { return "202212211436379_add_field__voucherNumber_Notes_in_VoucherDetail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
