// <auto-generated />
namespace ERP.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class update_tb_ItemPrice_Supplier : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_tb_ItemPrice_Supplier));
        
        string IMigrationMetadata.Id
        {
            get { return "202211071213407_update_tb_ItemPrice_Supplier"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
