// <auto-generated />
namespace ERP.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class remove_tb_Offer_Old : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_tb_Offer_Old));
        
        string IMigrationMetadata.Id
        {
            get { return "202210191257516_remove_tb_Offer_Old"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
