// <auto-generated />
namespace ERP.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_BranchId_InvoiceAmountFrom_DiscountAmount_in_Offer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_BranchId_InvoiceAmountFrom_DiscountAmount_in_Offer));
        
        string IMigrationMetadata.Id
        {
            get { return "202210221311022_add_BranchId_InvoiceAmountFrom_DiscountAmount_in_Offer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
