// <auto-generated />
namespace ERP.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_isactive_in_personTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_isactive_in_personTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202210031219101_add_isactive_in_personTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
