// <auto-generated />
namespace ERP.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_fields_Addres2_taxNumber_commRegNo_webSite_in_person : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_fields_Addres2_taxNumber_commRegNo_webSite_in_person));
        
        string IMigrationMetadata.Id
        {
            get { return "202209211412319_add_fields_Addres2_taxNumber_commRegNo_webSite_in_person"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
