// <auto-generated />
namespace ERP.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class change_stuctureDB_in_GeneralRecord_Voucher_masterDetails : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_stuctureDB_in_GeneralRecord_Voucher_masterDetails));
        
        string IMigrationMetadata.Id
        {
            get { return "202212191703456_change_stuctureDB_in_GeneralRecord_Voucher_masterDetails"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
