// <auto-generated />
namespace ERP.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_fields_emploees_details : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_fields_emploees_details));
        
        string IMigrationMetadata.Id
        {
            get { return "202209211820561_add_fields_emploees_details"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
