// <auto-generated />
namespace ERP.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_fields_tasksAndRequirements_in_Job : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_fields_tasksAndRequirements_in_Job));
        
        string IMigrationMetadata.Id
        {
            get { return "202209222320297_add_fields_tasksAndRequirements_in_Job"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
