// <auto-generated />
namespace ERP.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addField_SalesTaxPercentage_in_All_Invoices : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addField_SalesTaxPercentage_in_All_Invoices));
        
        string IMigrationMetadata.Id
        {
            get { return "202301091412584_addField_SalesTaxPercentage_in_All_Invoices"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
