// <auto-generated />
namespace ERP.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class remove_TB_PriceInvoice_add_QuoteOrderSell_Details : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_TB_PriceInvoice_add_QuoteOrderSell_Details));
        
        string IMigrationMetadata.Id
        {
            get { return "202303262222028_remove_TB_PriceInvoice_add_QuoteOrderSell_Details"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
