//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Web.NewFolder2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset
    {
        public int Id { get; set; }
        public Nullable<int> AccountTreeId { get; set; }
        public Nullable<int> AccountTreeParentId { get; set; }
        public Nullable<int> AccountTreeExpenseId { get; set; }
        public Nullable<int> AccountTreeDestructionId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> SafeId { get; set; }
        public Nullable<int> BankAccountId { get; set; }
        public bool IsIntialBalance { get; set; }
        public bool IsCarStore { get; set; }
        public bool IsNotCarStore { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public double Amount { get; set; }
        public bool IsDestruction { get; set; }
        public double DestructionAmount { get; set; }
        public Nullable<System.DateTime> OperationDate { get; set; }
        public double ScrapValue { get; set; }
        public int UsefulLife { get; set; }
        public string Notes { get; set; }
        public string Description { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual AccountsTree AccountsTree { get; set; }
        public virtual AccountsTree AccountsTree1 { get; set; }
        public virtual AccountsTree AccountsTree2 { get; set; }
        public virtual AccountsTree AccountsTree3 { get; set; }
        public virtual BankAccount BankAccount { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual Safe Safe { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
    }
}
