//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Web.NewFolder2
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralDaily
    {
        public int Id { get; set; }
        public Nullable<int> TransactionId { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<int> AccountsTreeId { get; set; }
        public double Debit { get; set; }
        public double Credit { get; set; }
        public Nullable<int> TransactionTypeId { get; set; }
        public string PaperNumber { get; set; }
        public Nullable<int> POSId { get; set; }
        public Nullable<int> ShiftId { get; set; }
        public string Notes { get; set; }
        public Nullable<int> BranchId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.Guid> TransactionShared { get; set; }
    
        public virtual AccountsTree AccountsTree { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual TransactionsType TransactionsType { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
    }
}
