//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Web.NewFolder2
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceInvoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PriceInvoice()
        {
            this.PriceInvoicesDetails = new HashSet<PriceInvoicesDetail>();
        }
    
        public int Id { get; set; }
        public System.Guid InvoiceGuid { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public double TotalQuantity { get; set; }
        public double TotalValue { get; set; }
        public double SalesTax { get; set; }
        public double ProfitTax { get; set; }
        public double InvoiceDiscount { get; set; }
        public double DiscountPercentage { get; set; }
        public double TotalDiscount { get; set; }
        public double Safy { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> IsFullReturned { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Person Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PriceInvoicesDetail> PriceInvoicesDetails { get; set; }
    }
}
