//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Web.NewFolder2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionOrderDetail
    {
        public int Id { get; set; }
        public Nullable<int> ProductionOrderId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public double Quantity { get; set; }
        public Nullable<int> StoreId { get; set; }
        public Nullable<int> ItemCostCalculateId { get; set; }
        public double ItemCost { get; set; }
        public double Quantitydamage { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ItemCostCalculation ItemCostCalculation { get; set; }
        public virtual Item Item { get; set; }
        public virtual ProductionOrder ProductionOrder { get; set; }
        public virtual Store Store { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
    }
}
