//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Web.NewFolder2
{
    using System;
    using System.Collections.Generic;
    
    public partial class SellBackInvoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SellBackInvoice()
        {
            this.CasesSellInvoiceHistories = new HashSet<CasesSellInvoiceHistory>();
            this.SellBackInvoiceIncomes = new HashSet<SellBackInvoiceIncome>();
            this.SellBackInvoicesDetails = new HashSet<SellBackInvoicesDetail>();
        }
    
        public int Id { get; set; }
        public System.Guid InvoiceGuid { get; set; }
        public bool BySaleMen { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> SellInvoiceId { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> PaymentTypeId { get; set; }
        public Nullable<int> SafeId { get; set; }
        public Nullable<int> BankAccountId { get; set; }
        public double TotalQuantity { get; set; }
        public double TotalValue { get; set; }
        public double TotalExpenses { get; set; }
        public double PayedValue { get; set; }
        public double RemindValue { get; set; }
        public double SalesTax { get; set; }
        public double ProfitTax { get; set; }
        public double InvoiceDiscount { get; set; }
        public double DiscountPercentage { get; set; }
        public double TotalDiscount { get; set; }
        public double Safy { get; set; }
        public bool IsApprovalAccountant { get; set; }
        public bool IsApprovalStore { get; set; }
        public bool IsFinalApproval { get; set; }
        public Nullable<int> CaseId { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string Notes { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> ShiftOfflineID { get; set; }
    
        public virtual BankAccount BankAccount { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual Case Case { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CasesSellInvoiceHistory> CasesSellInvoiceHistories { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual PaymentType PaymentType { get; set; }
        public virtual Person Person { get; set; }
        public virtual Safe Safe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SellBackInvoiceIncome> SellBackInvoiceIncomes { get; set; }
        public virtual SellInvoice SellInvoice { get; set; }
        public virtual ShiftsOffline ShiftsOffline { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SellBackInvoicesDetail> SellBackInvoicesDetails { get; set; }
    }
}
