//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Web.NewFolder2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voucher
    {
        public int Id { get; set; }
        public bool IsVoucherPayment { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> AccountTreeFromId { get; set; }
        public Nullable<int> AccountTreeToId { get; set; }
        public Nullable<System.DateTime> VoucherDate { get; set; }
        public double Amount { get; set; }
        public string Notes { get; set; }
        public bool IsApproval { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual AccountsTree AccountsTree { get; set; }
        public virtual AccountsTree AccountsTree1 { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
    }
}
