//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using ERP.DAL.Models;

    public partial class Bank : BaseModel
    {
        public Bank()
        {
            this.BankAccounts = new HashSet<BankAccount>();
        }

        [ForeignKey(nameof(City))]
        public Nullable<Guid> CityId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<BankAccount> BankAccounts { get; set; }
        public virtual City City { get; set; }
    }
}
