//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using ERP.DAL.Models;

    public partial class BankAccount : BaseModel
    {
        public BankAccount()
        {
            this.Assets = new HashSet<Asset>();
            this.Cheques = new HashSet<Cheque>();
            this.ContractLoans = new HashSet<ContractLoan>();
            this.EmployeeGivingCustodies = new HashSet<EmployeeGivingCustody>();
            this.EmployeeReturnCashCustodies = new HashSet<EmployeeReturnCashCustody>();
            this.Maintenances = new HashSet<Maintenance>();
            this.PurchaseBackInvoices = new HashSet<PurchaseBackInvoice>();
            this.PurchaseInvoices = new HashSet<PurchaseInvoice>();
            this.SellBackInvoices = new HashSet<SellBackInvoice>();
            this.SellInvoices = new HashSet<SellInvoice>();
            this.SupplierPayments = new HashSet<SupplierPayment>();
            this.PointOfSaleBankAccount = new HashSet<PointOfSale>();
            this.PointOfSaleWallet = new HashSet<PointOfSale>();
            this.PointOfSaleCard = new HashSet<PointOfSale>();

        }
        [ForeignKey(nameof(AccountsTree))]
        public Nullable<Guid> AccountsTreeId { get; set; }
        [ForeignKey(nameof(Bank))]
        public Nullable<Guid> BankId { get; set; }
        public string AccountName { get; set; }
        public string AccountNo { get; set; }
        public string IBAN { get; set; }
        public string SwiftCode { get; set; }

        public virtual AccountsTree AccountsTree { get; set; }
        public virtual Bank Bank { get; set; }

        public virtual ICollection<Asset> Assets { get; set; }
        public virtual ICollection<Cheque> Cheques { get; set; }
        public virtual ICollection<ContractLoan> ContractLoans { get; set; }
        public virtual ICollection<EmployeeGivingCustody> EmployeeGivingCustodies { get; set; }
        public virtual ICollection<EmployeeReturnCashCustody> EmployeeReturnCashCustodies { get; set; }
        public virtual ICollection<Maintenance> Maintenances { get; set; }
        [InverseProperty(nameof(PointOfSale.BankAccount))]
        public virtual ICollection<PointOfSale> PointOfSaleBankAccount { get; set; }
        public virtual ICollection<PurchaseBackInvoice> PurchaseBackInvoices { get; set; }
        public virtual ICollection<PurchaseInvoice> PurchaseInvoices { get; set; }
        public virtual ICollection<SellBackInvoice> SellBackInvoices { get; set; }
        public virtual ICollection<SellInvoice> SellInvoices { get; set; }
        public virtual ICollection<SupplierPayment> SupplierPayments { get; set; }
        [InverseProperty(nameof(PointOfSale.BankAccountWallet))]
        public virtual ICollection<PointOfSale> PointOfSaleWallet { get; set; }
        [InverseProperty(nameof(PointOfSale.BankAccountCard))]
        public virtual ICollection<PointOfSale> PointOfSaleCard { get; set; }

    }
}
