//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using ERP.DAL.Models;

    public partial class CasesSellInvoiceHistory : BaseModel
    {
        [ForeignKey(nameof(Case))]
        public Nullable<int> CaseId { get; set; }
        [ForeignKey(nameof(SellInvoice))]
        public Nullable<Guid> SellInvoiceId { get; set; }
        [ForeignKey(nameof(SellBackInvoice))]
        public Nullable<Guid> SellBackInvoiceId { get; set; }
        public bool IsSellInvoice { get; set; }
    
        public virtual Case Case { get; set; }
        public virtual SellBackInvoice SellBackInvoice { get; set; }
        public virtual SellInvoice SellInvoice { get; set; }
    }
}
