//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using ERP.DAL.Models;

    public partial class CasesPurchaseInvoiceHistory : BaseModel
    {
        [ForeignKey(nameof(Case))]
        public Nullable<int> CaseId { get; set; }
        [ForeignKey(nameof(PurchaseInvoice))]
        public Nullable<Guid> PurchaseInvoiceId { get; set; }
        [ForeignKey(nameof(PurchaseBackInvoice))]
        public Nullable<Guid> PurchaseBackInvoiceId { get; set; }
        public bool IsPurchaseInvoice { get; set; }
    
        public virtual Case Case { get; set; }
        public virtual PurchaseBackInvoice PurchaseBackInvoice { get; set; }
        public virtual PurchaseInvoice PurchaseInvoice { get; set; }
    }
}
