//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    using ERP.DAL.Models;

    public partial class ContractSchedulingsMain : BaseModel
    {
        public Nullable<int> MonthNum { get; set; }
        public Nullable<int> YearNum { get; set; }
        public Nullable<System.DateTime> MonthYear { get; set; }
        public double TotalSalaries { get; set; }
        public int Status { get; set; }
    }
}
