//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using ERP.DAL.Models;

    public partial class ContractScheduling : BaseModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContractScheduling()
        {
            this.ContractAttendanceLeavings = new HashSet<ContractAttendanceLeaving>();
            this.ContractLoans = new HashSet<ContractLoan>();
            this.ContractLoanSchedulings = new HashSet<ContractLoanScheduling>();
            this.ContractSalaryAdditions = new HashSet<ContractSalaryAddition>();
            this.ContractSalaryPenalties = new HashSet<ContractSalaryPenalty>();
            this.ContractSchedulingAbsences = new HashSet<ContractSchedulingAbsence>();
            this.ContractSchedulingProductions = new HashSet<ContractSchedulingProduction>();
        }

        [ForeignKey(nameof(Contract))]
        public Nullable<Guid> ContractId { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> MonthYear { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public bool IsApproval { get; set; }
        public bool IsPayed { get; set; }
        public double TotalSalaryAddAllowances { get; set; }
        public double TotalSalaryAddition { get; set; }
        public double TotalEveryMonthSalaryPenaltie { get; set; }
        public double TotalSalaryPenaltie { get; set; }
        public double TotalAmountAbsences { get; set; }
        public double LoanValue { get; set; }
        public double Safy { get; set; }
        public double PayedValue { get; set; }
        public double RemindValue { get; set; }
        public string Notes { get; set; }
        public virtual Contract Contract { get; set; }

        public virtual ICollection<ContractAttendanceLeaving> ContractAttendanceLeavings { get; set; }
        public virtual ICollection<ContractLoan> ContractLoans { get; set; }
        public virtual ICollection<ContractLoanScheduling> ContractLoanSchedulings { get; set; }
        public virtual ICollection<ContractSalaryAddition> ContractSalaryAdditions { get; set; }
        public virtual ICollection<ContractSalaryPenalty> ContractSalaryPenalties { get; set; }
        public virtual ICollection<ContractSchedulingAbsence> ContractSchedulingAbsences { get; set; }
        public virtual ICollection<ContractSchedulingProduction> ContractSchedulingProductions { get; set; }
    }
}
