//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using ERP.DAL.Models;

    public partial class GeneralRecord : BaseModel
    {
        public GeneralRecord()
        {
            this.GeneralRecordDetails = new HashSet<GeneralRecordDetail>();
        }
        [ForeignKey(nameof(Branch))]
        public Nullable<Guid> BranchId { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string Notes { get; set; }
        public bool IsApproval { get; set; }
        public string GeneralRecordNumber { get; set; }

        public virtual Branch Branch { get; set; }
        public virtual ICollection<GeneralRecordDetail> GeneralRecordDetails { get; set; }
    }
}
