//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using ERP.DAL.Models;

    public partial class Group : BaseModel
    {
        public Group()
        {
            this.ChildrenGroups = new HashSet<Group>();
            this.ItemsBaseGroup = new HashSet<Item>();
            this.ItemsSellGroup = new HashSet<Item>();
            this.ItemCustomSellPrices = new HashSet<ItemCustomSellPrice>();
        }
        [ForeignKey(nameof(GroupType))]
        public Nullable<int> GroupTypeId { get; set; }
        [ForeignKey(nameof(ParentGroup))]
        public Nullable<Guid> ParentId { get; set; }
        public string Name { get; set; }
        public string GroupCode { get; set; }

        //Group
        public virtual Group ParentGroup { get; set; }
        public virtual GroupType GroupType { get; set; }


        //Groups1
        public virtual ICollection<Group> ChildrenGroups { get; set; }
        //Items
        [InverseProperty(nameof(Item.GroupBasic))]
        public virtual ICollection<Item> ItemsBaseGroup { get; set; }
        //Items1
        [InverseProperty(nameof(Item.GroupSell))]
        public virtual ICollection<Item> ItemsSellGroup { get; set; }
        public virtual ICollection<ItemCustomSellPrice> ItemCustomSellPrices { get; set; }

    }
}
