//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using ERP.DAL.Models;

    public partial class Installment : BaseModel
    {
        public Installment()
        {
            this.InstallmentSchedules = new HashSet<InstallmentSchedule>();
        }

        [ForeignKey(nameof(SellInvoice))]
        public Nullable<Guid> SellInvoiceId { get; set; }
        public double PayedValue { get; set; }
        public int Duration { get; set; }
        public double RemindValue { get; set; }
        public double ProfitValue { get; set; }
        public double TotalValue { get; set; }
        public double CommissionVal { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        [ForeignKey(nameof(CustomerIntialBalance))]
        public Nullable<Guid> IntialCustomerId { get; set; }

        public virtual PersonIntialBalance CustomerIntialBalance { get; set; }
        public virtual SellInvoice SellInvoice { get; set; }

        public virtual ICollection<InstallmentSchedule> InstallmentSchedules { get; set; }
    }
}
