//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using ERP.DAL.Models;

    public partial class InstallmentSchedule : BaseModel
    {

        [ForeignKey(nameof(Installment))]
        public Nullable<Guid> InstallmentId { get; set; }
        public double Amount { get; set; }
        public Nullable<System.DateTime> InstallmentDate { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }

        [ForeignKey(nameof(PersonSaleMen))]
        public Nullable<Guid> SaleMenId { get; set; }
        public bool PaidInTime { get; set; }
        public bool IsPayed { get; set; }
        [ForeignKey(nameof(Safe))]
        public Nullable<Guid> SafeId { get; set; }
        public virtual Installment Installment { get; set; }

        //Person
        public virtual Person PersonSaleMen { get; set; }
        public virtual Safe Safe { get; set; }
    }
}
