//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using ERP.DAL.Models;

    public partial class InventoryInvoice : BaseModel
    {
        public InventoryInvoice()
        {
            this.InventoryInvoiceDetails = new HashSet<InventoryInvoiceDetail>();
        }
        public System.DateTime InvoiceDate { get; set; }
        public string InvoiceNumber { get; set; }

        [ForeignKey(nameof(Branch))]
        public Nullable<Guid> BranchId { get; set; }

        [ForeignKey(nameof(Store))]
        public Nullable<Guid> StoreId { get; set; }
        public double TotalDifferenceAmount { get; set; }

        [ForeignKey(nameof(ItemCostCalculation))]
        public Nullable<int> ItemCostCalculateId { get; set; }
        public string Notes { get; set; }

    
        public virtual Branch Branch { get; set; }
        public virtual ItemCostCalculation ItemCostCalculation { get; set; }
        public virtual Store Store { get; set; }


        public virtual ICollection<InventoryInvoiceDetail> InventoryInvoiceDetails { get; set; }
    }
}
