//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using ERP.DAL.Models;

    public partial class ItemSerial : BaseModel
    {
        public ItemSerial()
        {
            this.CasesItemSerialHistories = new HashSet<CasesItemSerialHistory>();
            this.MaintenanceDetails = new HashSet<MaintenanceDetail>();
            this.MaintenanceSpareParts = new HashSet<MaintenanceSparePart>();
            this.SellBackInvoicesDetails = new HashSet<SellBackInvoicesDetail>();
            this.SellInvoicesDetails = new HashSet<SellInvoicesDetail>();
            this.StoresTransferDetails = new HashSet<StoresTransferDetail>();
        }

        [ForeignKey(nameof(Item))]
        public Nullable<Guid> ItemId { get; set; }
        public string SerialNumber { get; set; }

        [ForeignKey(nameof(SerialCas))]
        public Nullable<int> SerialCaseId { get; set; }

        [ForeignKey(nameof(ProductionOrder))]
        public Nullable<Guid> ProductionOrderId { get; set; }      

        public Nullable<bool> IsItemIntial { get; set; }

        [ForeignKey(nameof(Maintenance))]
        public Nullable<Guid> MaintenanceId { get; set; }

        [ForeignKey(nameof(SellInvoice))]
        public Nullable<Guid> SellInvoiceId { get; set; }

        [ForeignKey(nameof(Store))]
        public Nullable<Guid> CurrentStoreId { get; set; }

        public Nullable<System.DateTime> ExpirationDate { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Maintenance Maintenance { get; set; }
        public virtual ProductionOrder ProductionOrder { get; set; }
        public virtual SellInvoice SellInvoice { get; set; }
        public virtual SerialCas SerialCas { get; set; }
        public virtual Store Store { get; set; }


        public virtual ICollection<CasesItemSerialHistory> CasesItemSerialHistories { get; set; }
        public virtual ICollection<MaintenanceDetail> MaintenanceDetails { get; set; }
        public virtual ICollection<MaintenanceSparePart> MaintenanceSpareParts { get; set; }
        public virtual ICollection<SellBackInvoicesDetail> SellBackInvoicesDetails { get; set; }
        public virtual ICollection<SellInvoicesDetail> SellInvoicesDetails { get; set; }
        public virtual ICollection<StoresTransferDetail> StoresTransferDetails { get; set; }
    }
}
