//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using ERP.DAL.Models;

    public partial class ItemIntialBalance : BaseModel
    {
        [ForeignKey(nameof(AccountTree))]
        public Nullable<Guid> AccountTreeId { get; set; }
        public Nullable<System.DateTime> DateIntial { get; set; }
        [ForeignKey(nameof(Item))]
        public Nullable<Guid> ItemId { get; set; }
        public double Quantity { get; set; }
        public double Price { get; set; }
        public double Amount { get; set; }
        [ForeignKey(nameof(Store))]
        public Nullable<Guid> StoreId { get; set; }
        public bool IsApproval { get; set; }
    
        public virtual AccountsTree AccountTree { get; set; }
        public virtual Item Item { get; set; }
        public virtual Store Store { get; set; }
    }
}
