//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using ERP.DAL.Models;

    public partial class Maintenance : BaseModel
    {
        public Maintenance()
        {
            this.ItemSerials = new HashSet<ItemSerial>();
            this.MaintenanceCaseHistories = new HashSet<MaintenanceCaseHistory>();
            this.MaintenanceDetails = new HashSet<MaintenanceDetail>();
        }
    
        public string InvoiceNumber { get; set; }
        [ForeignKey(nameof(Store))]
        public Nullable<Guid> StoreId { get; set; }
        public bool BySaleMen { get; set; }
        [ForeignKey(nameof(EmployeeSaleMen))]
        public Nullable<Guid> EmployeeSaleMenId { get; set; }
        [ForeignKey(nameof(EmployeeResponse))]
        public Nullable<Guid> EmployeeResponseId { get; set; }
        [ForeignKey(nameof(SellInvoice))]
        public Nullable<Guid> SellInvoiceId { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        [ForeignKey(nameof(Person))]
        public Nullable<Guid> CustomerId { get; set; }
        [ForeignKey(nameof(Branch))]
        public Nullable<Guid> BranchId { get; set; }
        [ForeignKey(nameof(PaymentType))]
        public Nullable<int> PaymentTypeId { get; set; }
        [ForeignKey(nameof(Safe))]
        public Nullable<Guid> SafeId { get; set; }
        [ForeignKey(nameof(BankAccount))]
        public Nullable<Guid> BankAccountId { get; set; }
        public double DiscountPercentage { get; set; }
        public double InvoiceDiscount { get; set; }
        public double TotalDiscount { get; set; }
        public double TotalIncomes { get; set; }
        public double TotalSpareParts { get; set; }
        public double PayedValue { get; set; }
        public double RemindValue { get; set; }
        public double Safy { get; set; }
        [ForeignKey(nameof(MaintenanceCas))]
        public Nullable<int> MaintenanceCaseId { get; set; }
        public bool IsFinalApproval { get; set; }
        public bool HasCost { get; set; }
        public bool HasGuarantee { get; set; }
        public string Notes { get; set; }
        public bool IsApprovalAccountant { get; set; }
        public bool IsApprovalStore { get; set; }
        [ForeignKey(nameof(StoreReceipt))]
        public Nullable<Guid> StoreReceiptId { get; set; }
        public Nullable<System.DateTime> ReceiptDate { get; set; }

        public virtual Store Store { get; set; }
        //Employee
        public virtual Employee EmployeeResponse { get; set; }
        //Employee1
        public virtual Employee EmployeeSaleMen { get; set; }
        public virtual SellInvoice SellInvoice { get; set; }
        public virtual Person Person { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual PaymentType PaymentType { get; set; }
        public virtual Safe Safe { get; set; }
        public virtual BankAccount BankAccount { get; set; }
        //Store1
        public virtual Store StoreReceipt { get; set; }
        public virtual MaintenanceCas MaintenanceCas { get; set; }


        public virtual ICollection<ItemSerial> ItemSerials { get; set; }
        public virtual ICollection<MaintenanceCaseHistory> MaintenanceCaseHistories { get; set; }
        public virtual ICollection<MaintenanceDetail> MaintenanceDetails { get; set; }
    }
}
