//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using ERP.DAL.Models;

    public partial class MaintenanceDetail: BaseModel
    {
        public MaintenanceDetail()
        {
            this.MaintenanceDamages = new HashSet<MaintenanceDamage>();
            this.MaintenanceIncomes = new HashSet<MaintenanceIncome>();
            this.MaintenanceSpareParts = new HashSet<MaintenanceSparePart>();
        }
    
        public System.Guid RecordGuid { get; set; }

        [ForeignKey(nameof(Maintenance))]
        public Nullable<Guid> MaintenanceId { get; set; }

        [ForeignKey(nameof(Item))]
        public Nullable<Guid> ItemId { get; set; }

        [ForeignKey(nameof(ItemSerial))]
        public Nullable<Guid> ItemSerialId { get; set; }

        [ForeignKey(nameof(MaintenProblemType))]
        public Nullable<Guid> MaintenProblemTypeId { get; set; }

        [ForeignKey(nameof(MaintenanceCas))]
        public Nullable<int> MaintenanceCaseId { get; set; }

        public double TotalItemDiscount { get; set; }
        public double TotalItemIncomes { get; set; }
        public double TotalItemSpareParts { get; set; }
        public double ItemSafy { get; set; }
        public string Note { get; set; }

    
        public virtual Item Item { get; set; }
        public virtual ItemSerial ItemSerial { get; set; }
        public virtual MaintenanceCas MaintenanceCas { get; set; }
        public virtual Maintenance Maintenance { get; set; }
        public virtual MaintenProblemType MaintenProblemType { get; set; }


        public virtual ICollection<MaintenanceIncome> MaintenanceIncomes { get; set; }
        public virtual ICollection<MaintenanceSparePart> MaintenanceSpareParts { get; set; }
        public virtual ICollection<MaintenanceDamage> MaintenanceDamages { get; set; }
    }
}
