//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using ERP.DAL.Models;

    public partial class Notification : BaseModel
    {
        public Notification()
        {
            this.NotificationEmployees = new HashSet<NotificationEmployee>();
        }
        [ForeignKey(nameof(NotificationType))]
        public Nullable<int> NotificationTypeId { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public double Amount { get; set; }
        public bool IsClosed { get; set; }
        public bool IsPeriodic { get; set; }
        public Nullable<Guid> RefNumber { get; set; }
        public DateTime? StartAlertDate { get; set; }

        public virtual NotificationType NotificationType { get; set; }
        public virtual ICollection<NotificationEmployee> NotificationEmployees { get; set; }
    }
}
