//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using ERP.DAL.Models;

    public partial class PagesRole : BaseModel
    {
        //«·’›Õ«  ’⁄»   €Ì— ÂÌ 
        [ForeignKey(nameof(Role))]
        public Nullable<Guid> RoleId { get; set; }

        [ForeignKey(nameof(Page))]
        public Nullable<int> PageId { get; set; }
    
        public virtual Page Page { get; set; }
        public virtual Role Role { get; set; }
    }
}
