//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations.Schema;

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    using ERP.DAL.Models;

    public partial class PersonCategory : BaseModel
    {
        public PersonCategory()
        {
            this.Persons = new HashSet<Person>();
        }
    
        public bool IsCustomer { get; set; }
        public string Name { get; set; }
        [ForeignKey(nameof(AccountTree))]
        public Nullable<Guid> AccountTreeId { get; set; }   
        public virtual ICollection<Person> Persons { get; set; }

        public AccountsTree AccountTree { get; set; }
    }
}
