//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using ERP.DAL.Models;

    public partial class PointOfSale : BaseModel
    {
        public PointOfSale()
        {
            this.ShiftsOfflines = new HashSet<ShiftsOffline>();
        }
    
        public string Name { get; set; }

        [ForeignKey(nameof(Branch))]
        public Nullable<Guid> BrunchId { get; set; }
        [ForeignKey(nameof(Safe))]
        public Nullable<Guid> SafeID { get; set; }

        [ForeignKey(nameof(BankAccount))]
        public Nullable<Guid> BankAccountID { get; set; }

        [ForeignKey(nameof(Store))]
        public Nullable<Guid> StoreID { get; set; }

        [ForeignKey(nameof(PricingPolicy))]
        public Nullable<Guid> DefaultPricePolicyID { get; set; }
        [ForeignKey(nameof(PersonCustomer))]
        public Nullable<Guid> DefaultCustomerID { get; set; }
        [ForeignKey(nameof(PersonSupplier))]
        public Nullable<Guid> DefaultSupplierID { get; set; }
        [ForeignKey(nameof(PaymentType))]
        public Nullable<int> DefaultPaymentID { get; set; }
        public bool CanDiscount { get; set; }
        public bool CanChangePrice { get; set; }
        [ForeignKey(nameof(BankAccountWallet))]
        public Nullable<Guid> DefaultBankWalletId { get; set; }
        [ForeignKey(nameof(BankAccountCard))]
        public Nullable<Guid> DefaultBankCardId { get; set; }

        public virtual BankAccount BankAccount { get; set; }
        public virtual PaymentType PaymentType { get; set; }
        public virtual Person PersonCustomer { get; set; }
        public virtual Person PersonSupplier { get; set; }
        public virtual PricingPolicy PricingPolicy { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual Safe Safe { get; set; }
        public virtual Store Store { get; set; }
        public virtual BankAccount BankAccountWallet { get; set; }
        public virtual BankAccount BankAccountCard { get; set; }

        public virtual ICollection<ShiftsOffline> ShiftsOfflines { get; set; }
    }
}
