//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    using ERP.DAL.Models;

    public partial class PricingPolicy : BaseModel
    {
        public PricingPolicy()
        {
            this.ItemPrices = new HashSet<ItemPrice>();
            this.PointOfSales = new HashSet<PointOfSale>();
        }
    
        public string Name { get; set; }
    
        public virtual ICollection<ItemPrice> ItemPrices { get; set; }
        public virtual ICollection<PointOfSale> PointOfSales { get; set; }
    }
}
