//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using ERP.DAL.Models;

    public partial class PricesChanx : BaseModel
    {
        public bool IsPurchasePrice { get; set; }

        [ForeignKey(nameof(Item))]
        public Nullable<Guid> ItemId { get; set; }

        public Nullable<double> Price { get; set; }
        public string Notes { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
