//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using ERP.DAL.Models;

    public partial class PriceInvoice : BaseModel
    {
        public PriceInvoice()
        {
            this.PriceInvoicesDetails = new HashSet<PriceInvoicesDetail>();
        }

        [ForeignKey(nameof(PersonCustomer))]
        public Nullable<Guid> CustomerId { get; set; }
        [ForeignKey(nameof(Branch))]
        public Nullable<Guid> BranchId { get; set; }

        public System.Guid InvoiceGuid { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public double TotalQuantity { get; set; }
        public double TotalValue { get; set; }
        public double SalesTax { get; set; }
        public double ProfitTax { get; set; }
        public double InvoiceDiscount { get; set; }
        public double DiscountPercentage { get; set; }
        public double TotalDiscount { get; set; }
        public double Safy { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> IsFullReturned { get; set; }
        public string InvoiceNumber { get; set; }


        public virtual Person PersonCustomer { get; set; }
        public virtual Branch Branch { get; set; }

        public virtual ICollection<PriceInvoicesDetail> PriceInvoicesDetails { get; set; }
    }
}
