//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using ERP.DAL.Models;

    public partial class ProductionOrderDetail : BaseModel
    {
        [ForeignKey(nameof(ProductionOrder))]
        public Nullable<Guid> ProductionOrderId { get; set; }    
        [ForeignKey(nameof(ItemProduction))]
        public Nullable<Guid> ItemProductionId { get; set; }
        [ForeignKey(nameof(Item))]
        public Nullable<Guid> ItemId { get; set; }
        public double Quantity { get; set; }
        //[ForeignKey(nameof(Store))]
        //public Nullable<Guid> StoreId { get; set; }
        [ForeignKey(nameof(ItemCostCalculation))]
        public Nullable<int> ItemCostCalculateId { get; set; }
        public double ItemCost { get; set; }
        public double Quantitydamage { get; set; }
        [ForeignKey(nameof(ProductionType))]
        public Nullable<int> ProductionTypeId { get; set; }
        public Nullable<int> ComplexProductionIndex { get; set; }//›Â—”… «· Ê·Ì›«  ·«„— «·«‰ «Ã «·Ê«Õœ ·⁄—÷Â« „‰›’·Â 
        public virtual ItemCostCalculation ItemCostCalculation { get; set; }
        public virtual Item Item { get; set; }
        public virtual ProductionOrder ProductionOrder { get; set; }
        //public virtual Store Store { get; set; }
        public virtual ItemProduction ItemProduction { get; set; }
        public virtual ProductionType ProductionType { get; set; }
    }
}
