//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using ERP.DAL.Models;

    public partial class ProductionOrderExpens : BaseModel
    {
        [ForeignKey(nameof(ProductionOrder))]
        public Nullable<Guid> ProductionOrderId { get; set; }

        //ExpenseTypeId
        [ForeignKey(nameof(ExpenseTypeAccountTree))]
        public Nullable<Guid> ExpenseTypeAccountTreeId { get; set; }

        public double Amount { get; set; }
        public string Note { get; set; }
    
        //AccountsTree
        public virtual AccountsTree ExpenseTypeAccountTree { get; set; }
        public virtual ProductionOrder ProductionOrder { get; set; }
    }
}
