//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using ERP.DAL.Models;

    public partial class PurchaseBackInvoicesExpens : BaseModel
    {
        [ForeignKey(nameof(PurchaseBackInvoice))]
        public Nullable<Guid> PurchaseBackInvoiceId { get; set; }

        //ExpenseTypeId
        [ForeignKey(nameof(ExpenseTypeAccountsTree))]
        public Nullable<Guid> ExpenseTypeAccountsTreeID { get; set; }
        public double Amount { get; set; }


        //AccountsTree
        public virtual AccountsTree ExpenseTypeAccountsTree { get; set; }
        public virtual PurchaseBackInvoice PurchaseBackInvoice { get; set; }
    }
}
