//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    using ERP.DAL.Models;

    public partial class Role : BaseModel
    {
        public Role()
        {
            this.PagesRoles = new HashSet<PagesRole>();
            this.Users = new HashSet<User>();
        }

        public string Name { get; set; }
        public bool IsAdmin { get; set; }

        public virtual ICollection<PagesRole> PagesRoles { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
