//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using ERP.DAL.Models;
    using ERP.DAL.Utilites;

    public partial class Safe : BaseModel
    {
        public Safe()
        {
            this.Assets = new HashSet<Asset>();
            this.ContractLoans = new HashSet<ContractLoan>();
            this.CustomerPayments = new HashSet<CustomerPayment>();
            this.EmployeeGivingCustodies = new HashSet<EmployeeGivingCustody>();
            this.EmployeeReturnCashCustodies = new HashSet<EmployeeReturnCashCustody>();
            this.ExpenseIncomes = new HashSet<ExpenseIncome>();
            this.Maintenances = new HashSet<Maintenance>();
            this.PointOfSales = new HashSet<PointOfSale>();
            this.PurchaseBackInvoices = new HashSet<PurchaseBackInvoice>();
            this.PurchaseInvoices = new HashSet<PurchaseInvoice>();
            this.SellBackInvoices = new HashSet<SellBackInvoice>();
            this.SellInvoices = new HashSet<SellInvoice>();
            this.SupplierPayments = new HashSet<SupplierPayment>();
            this.EmployeeSafes = new HashSet<EmployeeSafe>();
        }

        [ForeignKey(nameof(AccountsTree))]
        public Nullable<Guid> AccountsTreeId { get; set; }

        //ResoponsibleId
        //[ForeignKey(nameof(ResoponsiblePerson)),ReNamed("ResoponsibleId")]
        //public Nullable<Guid> ResoponsiblePersonId { get; set; }

        [ForeignKey(nameof(Branch))]
        public Nullable<Guid> BranchId { get; set; }

        public string Name { get; set; }

    
        public virtual AccountsTree AccountsTree { get; set; }
        ////Person
        //public virtual Person ResoponsiblePerson { get; set; }
        public virtual Branch Branch { get; set; }


        public virtual ICollection<Asset> Assets { get; set; }
        public virtual ICollection<ContractLoan> ContractLoans { get; set; }
        public virtual ICollection<CustomerPayment> CustomerPayments { get; set; }
        public virtual ICollection<EmployeeGivingCustody> EmployeeGivingCustodies { get; set; }
        public virtual ICollection<EmployeeReturnCashCustody> EmployeeReturnCashCustodies { get; set; }
        public virtual ICollection<ExpenseIncome> ExpenseIncomes { get; set; }
        public virtual ICollection<Maintenance> Maintenances { get; set; }
        public virtual ICollection<PointOfSale> PointOfSales { get; set; }
        public virtual ICollection<PurchaseBackInvoice> PurchaseBackInvoices { get; set; }
        public virtual ICollection<PurchaseInvoice> PurchaseInvoices { get; set; }
        public virtual ICollection<SellBackInvoice> SellBackInvoices { get; set; }
        public virtual ICollection<SellInvoice> SellInvoices { get; set; }
        public virtual ICollection<SupplierPayment> SupplierPayments { get; set; }
        public virtual ICollection<EmployeeSafe> EmployeeSafes { get; set; }
    }
}
