//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using ERP.DAL.Models;

    public partial class SalaryPenalty: BaseModel
    {
        public SalaryPenalty()
        {
            this.ContractSalaryPenalties = new HashSet<ContractSalaryPenalty>();
        }
        [ForeignKey(nameof(SalaryPenaltyType))]
        public Nullable<Guid> SalaryPenaltyTypeId { get; set; }
        public string Name { get; set; }
        
        public virtual ICollection<ContractSalaryPenalty> ContractSalaryPenalties { get; set; }
        public virtual SalaryPenaltyType SalaryPenaltyType { get; set; }
    }
}
