//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using ERP.DAL.Models;

    public partial class SaleMenArea : BaseModel
    {
        [ForeignKey(nameof(Area))]
        public Nullable<Guid> AreaId { get; set; }
        [ForeignKey(nameof(Person))]
        public Nullable<Guid> PersonId { get; set; }

        public virtual Area Area { get; set; }
        public virtual Person Person { get; set; }
    }
}
