//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using ERP.DAL.Models;

    public partial class SaleMenCustomer : BaseModel
    {
        [ForeignKey(nameof(Employee))]
        public Nullable<Guid> EmployeeId { get; set; }
        [ForeignKey(nameof(CustomerPerson))]
        public Nullable<Guid> CustomerId { get; set; }
    
        public virtual Employee Employee { get; set; }
        //Person
        public virtual Person CustomerPerson { get; set; }
    }
}
