//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using ERP.DAL.Models;
    using ERP.DAL.Utilites;

    public partial class SellBackInvoiceIncome : BaseModel
    {
        [ForeignKey(nameof(SellBackInvoice))]
        public Nullable<Guid> SellBackInvoiceId { get; set; }

        //IncomeTypeId
        [ForeignKey(nameof(IncomeTypeAccountTree)),ReNamed("IncomeTypeId")]
        public Nullable<Guid> IncomeTypeAccountTreeId { get; set; }
        public double Amount { get; set; }

        //AccountsTree
        public virtual AccountsTree IncomeTypeAccountTree { get; set; }
        public virtual SellBackInvoice SellBackInvoice { get; set; }
    }
}
