//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using ERP.DAL.Models;

    public partial class SellInvoice :BaseModel
    {
        public SellInvoice()
        {
            this.CasesSellInvoiceHistories = new HashSet<CasesSellInvoiceHistory>();
            this.CustomerPayments = new HashSet<CustomerPayment>();
            this.Installments = new HashSet<Installment>();
            this.ItemSerials = new HashSet<ItemSerial>();
            this.Maintenances = new HashSet<Maintenance>();
            this.SellBackInvoices = new HashSet<SellBackInvoice>();
            this.SellInvoiceIncomes = new HashSet<SellInvoiceIncome>();
            this.SellInvoicePayments = new HashSet<SellInvoicePayment>();
            this.SellInvoicesDetails = new HashSet<SellInvoicesDetail>();
            this.OfferSellInvoices = new HashSet<OfferSellInvoice>();
        }


        [ForeignKey(nameof(Employee))]
        public Nullable<Guid> EmployeeId { get; set; }
        [ForeignKey(nameof(PersonCustomer))]
        public Nullable<Guid> CustomerId { get; set; }
        [ForeignKey(nameof(Branch))]
        public Nullable<Guid> BranchId { get; set; }
        [ForeignKey(nameof(PaymentType))]
        public Nullable<int> PaymentTypeId { get; set; }
        [ForeignKey(nameof(Safe))]
        public Nullable<Guid> SafeId { get; set; }
        [ForeignKey(nameof(BankAccount))]
        public Nullable<Guid> BankAccountId { get; set; }
        [ForeignKey(nameof(ShiftsOffline))]
        public Nullable<Guid> ShiftOffLineID { get; set; }
        [ForeignKey(nameof(Case))]
        public Nullable<int> CaseId { get; set; }

        public bool BySaleMen { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public double TotalQuantity { get; set; }
        public double TotalValue { get; set; }
        public double TotalExpenses { get; set; }
        public double PayedValue { get; set; }
        public double RemindValue { get; set; }
        public double SalesTax { get; set; }
        public double ProfitTax { get; set; }
        public double InvoiceDiscount { get; set; }
        public double DiscountPercentage { get; set; }
        public double OffersDiscount { get; set; }
        public double TotalDiscount { get; set; }
        public double Safy { get; set; }
        public bool IsApprovalAccountant { get; set; }
        public bool IsApprovalStore { get; set; }
        public bool IsFinalApproval { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> IsFullReturned { get; set; }
        public string InvoiceNumPaper { get; set; }
        public string InvoiceNumber { get; set; }
        [ForeignKey(nameof(OrderSell))]
        public Nullable<Guid> OrderSellId { get; set; }

        public virtual BankAccount BankAccount { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual Case Case { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual PaymentType PaymentType { get; set; }
        public virtual Person PersonCustomer { get; set; }
        public virtual Safe Safe { get; set; }
        public virtual ShiftsOffline ShiftsOffline { get; set; }
        public virtual QuoteOrderSell OrderSell { get; set; }


        public virtual ICollection<Installment> Installments { get; set; }
        public virtual ICollection<ItemSerial> ItemSerials { get; set; }
        public virtual ICollection<Maintenance> Maintenances { get; set; }
        public virtual ICollection<CasesSellInvoiceHistory> CasesSellInvoiceHistories { get; set; }
        public virtual ICollection<CustomerPayment> CustomerPayments { get; set; }
        public virtual ICollection<SellBackInvoice> SellBackInvoices { get; set; }
        public virtual ICollection<SellInvoiceIncome> SellInvoiceIncomes { get; set; }
        public virtual ICollection<SellInvoicePayment> SellInvoicePayments { get; set; }
        public virtual ICollection<SellInvoicesDetail> SellInvoicesDetails { get; set; }
        public virtual ICollection<OfferSellInvoice> OfferSellInvoices { get; set; }
    }
}
