//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using ERP.DAL.Models;

    public partial class ShiftsOffline : BaseModel
    {
        public ShiftsOffline()
        {
            this.ExpenseIncomes = new HashSet<ExpenseIncome>();
            this.PurchaseBackInvoices = new HashSet<PurchaseBackInvoice>();
            this.PurchaseInvoices = new HashSet<PurchaseInvoice>();
            this.SellBackInvoices = new HashSet<SellBackInvoice>();
            this.SellInvoices = new HashSet<SellInvoice>();
            this.ContractLoans = new HashSet<ContractLoan>();
        }
        public Guid Id { get; set; }
        public string ShiftNumber { get; set; }

        [ForeignKey(nameof(PointOfSale))]
        public Guid PointOfSaleID { get; set; }

        public System.DateTime Date { get; set; }

        [ForeignKey(nameof(Employee))]
        public Guid EmployeeID { get; set; }

        public bool IsClosed { get; set; }
        public Nullable<System.DateTime> ClosedOn { get; set; }

        [ForeignKey(nameof(Closer))]
        public Nullable<Guid> ClosedBy { get; set; }

        public virtual Employee Employee { get; set; }
        public virtual PointOfSale PointOfSale { get; set; }
        public virtual User Closer { get; set; }

        public virtual ICollection<ExpenseIncome> ExpenseIncomes { get; set; }
        public virtual ICollection<PurchaseBackInvoice> PurchaseBackInvoices { get; set; }
        public virtual ICollection<PurchaseInvoice> PurchaseInvoices { get; set; }
        public virtual ICollection<SellBackInvoice> SellBackInvoices { get; set; }
        public virtual ICollection<SellInvoice> SellInvoices { get; set; }
        public virtual ICollection<ContractLoan> ContractLoans { get; set; }
    }
}
