//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using ERP.DAL.Models;

    public partial class StoreAdjustment : BaseModel
    {
        [ForeignKey(nameof(Store))]
        public Nullable<Guid> StoreId { get; set; }
        [ForeignKey(nameof(Item))]
        public Nullable<Guid> ItemId { get; set; }
        public Nullable<int> Difference { get; set; }
        public Nullable<double> Cost { get; set; }
        [ForeignKey(nameof(Person))]
        public Nullable<Guid> CustomerId { get; set; }
        public string Notes { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Person Person { get; set; }
        public virtual Store Store { get; set; }
    }
}
