//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using ERP.DAL.Models;

    public partial class Store : BaseModel
    {
        public Store()
        {
            this.InventoryInvoices = new HashSet<InventoryInvoice>();
            this.ItemIntialBalanceDetails = new HashSet<ItemIntialBalanceDetail>();
            this.ItemSerials = new HashSet<ItemSerial>();
            this.MaintenanceDamages = new HashSet<MaintenanceDamage>();
            this.MaintenancesStores = new HashSet<Maintenance>();
            this.MaintenancesStoreReceipts = new HashSet<Maintenance>();
            this.MaintenanceSpareParts = new HashSet<MaintenanceSparePart>();
            //this.ProductionOrderDetails = new HashSet<ProductionOrderDetail>();
            this.ProductionOrderReceipts = new HashSet<ProductionOrderReceipt>();
            this.ProductionStores = new HashSet<ProductionOrder>();
            this.ProductionUnderStores = new HashSet<ProductionOrder>();
            this.PurchaseBackInvoicesDetails = new HashSet<PurchaseBackInvoicesDetail>();
            this.PurchaseInvoicesDetails = new HashSet<PurchaseInvoicesDetail>();
            this.SaleMenStoreHistories = new HashSet<SaleMenStoreHistory>();
            this.SellBackInvoicesDetails = new HashSet<SellBackInvoicesDetail>();
            this.SellInvoicesDetails = new HashSet<SellInvoicesDetail>();
            this.StoreAdjustments = new HashSet<StoreAdjustment>();
            this.StoresTransfersFrom = new HashSet<StoresTransfer>();
            this.StoresTransfersTo = new HashSet<StoresTransfer>();
            this.DamageInvoices = new HashSet<DamageInvoice>();
            this.QuoteOrderSellDetails = new HashSet<QuoteOrderSellDetail>();
            this.EmployeeStores = new HashSet<EmployeeStore>();
        }

        [ForeignKey(nameof(AccountsTree))]
        public Nullable<Guid> AccountTreeId { get; set; }
        [ForeignKey(nameof(Branch))]
        public Nullable<Guid> BranchId { get; set; }
        public bool IsDamages { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }

        public virtual AccountsTree AccountsTree { get; set; }
        public virtual Branch Branch { get; set; }

        public virtual ICollection<InventoryInvoice> InventoryInvoices { get; set; }
        public virtual ICollection<ItemIntialBalanceDetail> ItemIntialBalanceDetails { get; set; }
        public virtual ICollection<ItemSerial> ItemSerials { get; set; }
        public virtual ICollection<MaintenanceDamage> MaintenanceDamages { get; set; }

        //Maintenances
        [InverseProperty(nameof(Maintenance.Store))]
        public virtual ICollection<Maintenance> MaintenancesStores { get; set; }

        //Maintenances1
        [InverseProperty(nameof(Maintenance.StoreReceipt))]
        public virtual ICollection<Maintenance> MaintenancesStoreReceipts { get; set; }

        public virtual ICollection<MaintenanceSparePart> MaintenanceSpareParts { get; set; }
        //public virtual ICollection<ProductionOrderDetail> ProductionOrderDetails { get; set; }
        public virtual ICollection<ProductionOrderReceipt> ProductionOrderReceipts { get; set; }

        //ProductionStore „Œ“‰ «· ’‰Ì⁄ «·‰Â«∆Ï
        [InverseProperty(nameof(ProductionOrder.ProductionStore))]
        public virtual ICollection<ProductionOrder> ProductionStores { get; set; }
        //ProductionStore „Œ“‰  Õ  «· ’‰Ì⁄ 
        [InverseProperty(nameof(ProductionOrder.ProductionUnderStore))]
        public virtual ICollection<ProductionOrder> ProductionUnderStores { get; set; }
        public virtual ICollection<PurchaseBackInvoicesDetail> PurchaseBackInvoicesDetails { get; set; }
        public virtual ICollection<PurchaseInvoicesDetail> PurchaseInvoicesDetails { get; set; }
        public virtual ICollection<SaleMenStoreHistory> SaleMenStoreHistories { get; set; }
        public virtual ICollection<SellBackInvoicesDetail> SellBackInvoicesDetails { get; set; }
        public virtual ICollection<SellInvoicesDetail> SellInvoicesDetails { get; set; }
        public virtual ICollection<StoreAdjustment> StoreAdjustments { get; set; }
        [InverseProperty(nameof(StoresTransfer.StoreFrom))]
        public virtual ICollection<StoresTransfer> StoresTransfersFrom { get; set; }
        [InverseProperty(nameof(StoresTransfer.StoreTo))]
        public virtual ICollection<StoresTransfer> StoresTransfersTo { get; set; }
        public virtual ICollection<PointOfSale> PointOfSales { get; set; }
        public virtual ICollection<DamageInvoice> DamageInvoices { get; set; }
        public virtual ICollection<QuoteOrderSellDetail> QuoteOrderSellDetails { get; set; }
        public virtual ICollection<EmployeeStore> EmployeeStores { get; set; }
    }
}
