//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using ERP.DAL.Models;

    public partial class StoresTransfer : BaseModel
    {
        public StoresTransfer()
        {
            this.StoresTransferDetails = new HashSet<StoresTransferDetail>();
            this.StoresTransferHistories = new HashSet<StoresTransferHistory>();
        }
    
        [ForeignKey(nameof(StoreFrom))]
        public Nullable<Guid> StoreFromId { get; set; }
        [ForeignKey(nameof(StoreTo))]
        public Nullable<Guid> StoreToId { get; set; }
        //public bool ForSaleMen { get; set; }
        [ForeignKey(nameof(EmployeeFrom))]
        public Nullable<Guid> EmployeeFromId { get; set; }
        [ForeignKey(nameof(EmployeeTo))]
        public Nullable<Guid> EmployeeToId { get; set; }
        //public bool SaleMenStatus { get; set; }
        //public bool SaleMenIsApproval { get; set; }
        public string Notes { get; set; }
        public System.DateTime TransferDate { get; set; }
        public string StoreTransferNumber { get; set; }
        public bool IsApprovalStore { get; set; }
        public bool IsRefusStore { get; set; }
        public bool IsFinalApproval { get; set; }
        [ForeignKey(nameof(StoresTransferCase))]
        public Nullable<int> StoresTransferCaseId { get; set; }
        //Employee
        public virtual Employee EmployeeFrom { get; set; }
        //Employee1
        public virtual Employee EmployeeTo { get; set; }
        //Store
        public virtual Store StoreFrom { get; set; }
        //Store1
        public virtual Store StoreTo { get; set; }
        public virtual StoresTransferCase StoresTransferCase { get; set; }
        public virtual ICollection<StoresTransferDetail> StoresTransferDetails { get; set; }
        public virtual ICollection<StoresTransferHistory> StoresTransferHistories { get; set; }
    }
}
