//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    using ERP.DAL.Models;

    public partial class TransactionsType : BaseModelInt
    {
        public TransactionsType()
        {
            this.GeneralDailies = new HashSet<GeneralDaily>();
        }
    
        public string Name { get; set; }
    
        public virtual ICollection<GeneralDaily> GeneralDailies { get; set; }
    }
}
