//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using ERP.DAL.Models;

    public partial class Unit : BaseModel 
    {
        public Unit()
        {
            this.ItemPrices = new HashSet<ItemPrice>();
            this.Items = new HashSet<Item>();
            this.ItemsConvertFrom = new HashSet<Item>();
            this.ItemUnits = new HashSet<ItemUnit>();
        }
    
        public string Name { get; set; }
    
        public virtual ICollection<ItemPrice> ItemPrices { get; set; }
        public virtual ICollection<ItemUnit> ItemUnits { get; set; }

        //Items
        [InverseProperty(nameof(Item.Unit))]
        public virtual ICollection<Item> Items { get; set; }

        //Items1
        [InverseProperty(nameof(Item.UnitConvertFrom))]
        public virtual ICollection<Item> ItemsConvertFrom { get; set; }
    }
}
