//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    using ERP.DAL.Models;

    public partial class VacationType : BaseModel
    {
        public VacationType()
        {
            this.ContractDefinitionVacations = new HashSet<ContractDefinitionVacation>();
            this.ContractSchedulingAbsences = new HashSet<ContractSchedulingAbsence>();
            this.ContractVacations = new HashSet<ContractVacation>();
        }
    
        public string Name { get; set; }
    
        public virtual ICollection<ContractDefinitionVacation> ContractDefinitionVacations { get; set; }
        public virtual ICollection<ContractSchedulingAbsence> ContractSchedulingAbsences { get; set; }
        public virtual ICollection<ContractVacation> ContractVacations { get; set; }
    }
}
