//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using ERP.DAL.Models;

    public partial class Voucher : BaseModel
    {
        public bool IsVoucherPayment { get; set; }
        [ForeignKey(nameof(Branch))]
        public Nullable<Guid> BranchId { get; set; }
        [ForeignKey(nameof(AccountsTreeFrom))]
        public Nullable<Guid> AccountTreeFromId { get; set; }
        [ForeignKey(nameof(AccountsTreeTo))]
        public Nullable<Guid> AccountTreeToId { get; set; }
        public Nullable<System.DateTime> VoucherDate { get; set; }

        public double Amount { get; set; }
        public string Notes { get; set; }
        public bool IsApproval { get; set; }
        public string VoucherNumber { get; set; }

        //AccountTree
        public virtual AccountsTree AccountsTreeFrom { get; set; }

        //AccountTree1
        public virtual AccountsTree AccountsTreeTo { get; set; }

        public virtual Branch Branch { get; set; }

    }
}
