//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    using ERP.DAL.Models;

    public partial class WorkingPeriod : BaseModel
    {
        public WorkingPeriod()
        {
            this.Shifts = new HashSet<Shift>();
        }
    
        public string Name { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public Nullable<System.TimeSpan> DelayFrom { get; set; }
        public Nullable<System.TimeSpan> AbsenceOf { get; set; }
        public string Notes { get; set; }
    
        public virtual ICollection<Shift> Shifts { get; set; }
    }
}
