//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Web.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contract()
        {
            this.ContractDefinitionVacations = new HashSet<ContractDefinitionVacation>();
            this.ContractSalaryAdditions = new HashSet<ContractSalaryAddition>();
            this.ContractSalaryPenalties = new HashSet<ContractSalaryPenalty>();
            this.ContractSchedulings = new HashSet<ContractScheduling>();
            this.ContractVacations = new HashSet<ContractVacation>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ContractTypeId { get; set; }
        public Nullable<int> ContractSalaryTypeId { get; set; }
        public Nullable<System.Guid> EmployeeId { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public int NumberMonths { get; set; }
        public double Salary { get; set; }
        public double OverTime { get; set; }
        public double TotalSalaryAddition { get; set; }
        public double TotalSalaryPenalties { get; set; }
        public double TotalDefinitionVacations { get; set; }
        public bool IsApproval { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> FinishedDate { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<System.Guid> DeletedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractDefinitionVacation> ContractDefinitionVacations { get; set; }
        public virtual ContractSalaryType ContractSalaryType { get; set; }
        public virtual ContractType ContractType { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractSalaryAddition> ContractSalaryAdditions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractSalaryPenalty> ContractSalaryPenalties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractScheduling> ContractSchedulings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractVacation> ContractVacations { get; set; }
    }
}
