//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Web.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Cheques = new HashSet<Cheque>();
            this.Contracts = new HashSet<Contract>();
            this.CustomerPayments = new HashSet<CustomerPayment>();
            this.EmployeeBranches = new HashSet<EmployeeBranch>();
            this.EmployeeGivingCustodies = new HashSet<EmployeeGivingCustody>();
            this.EmployeeReturnCashCustodies = new HashSet<EmployeeReturnCashCustody>();
            this.EmployeeReturnCustodies = new HashSet<EmployeeReturnCustody>();
            this.Maintenances = new HashSet<Maintenance>();
            this.Maintenances1 = new HashSet<Maintenance>();
            this.NotificationEmployees = new HashSet<NotificationEmployee>();
            this.ProductionLineEmployees = new HashSet<ProductionLineEmployee>();
            this.SaleMenCustomers = new HashSet<SaleMenCustomer>();
            this.SaleMenStoreHistories = new HashSet<SaleMenStoreHistory>();
            this.SellBackInvoices = new HashSet<SellBackInvoice>();
            this.SellInvoices = new HashSet<SellInvoice>();
            this.Shifts = new HashSet<Shift>();
            this.ShiftsOfflines = new HashSet<ShiftsOffline>();
            this.Stores = new HashSet<Store>();
            this.Stores1 = new HashSet<Store>();
            this.StoresTransfers = new HashSet<StoresTransfer>();
            this.StoresTransfers1 = new HashSet<StoresTransfer>();
            this.VacationDays = new HashSet<VacationDay>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> PersonId { get; set; }
        public Nullable<System.Guid> StoreId { get; set; }
        public Nullable<System.Guid> DepartmentId { get; set; }
        public Nullable<System.Guid> JobId { get; set; }
        public bool IsSaleMen { get; set; }
        public string NationalID { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public Nullable<int> SocialStatusId { get; set; }
        public Nullable<System.DateTime> DateOfHiring { get; set; }
        public bool HasRole { get; set; }
        public double CommissionPercentage { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<System.Guid> DeletedBy { get; set; }
        public Nullable<System.Guid> Store_Id { get; set; }
        public bool Is100Percentage { get; set; }
        public string PassportNumber { get; set; }
        public Nullable<System.DateTime> PassportExpirationDate { get; set; }
        public string PassportIssuer { get; set; }
        public string PassportJob { get; set; }
        public string ResidenceNumber { get; set; }
        public Nullable<System.DateTime> ResidenceExpirationDate { get; set; }
        public string ResidenceIssuer { get; set; }
        public string ResidenceJob { get; set; }
        public Nullable<int> MedicalInsurancePolicyNumber { get; set; }
        public string MedicalInsuranceCategory { get; set; }
        public Nullable<System.DateTime> MedicalInsuranceExpirationDate { get; set; }
        public Nullable<System.DateTime> MedicalInsuranceReleaseDate { get; set; }
        public string MedicalInsuranceCompany { get; set; }
        public string SocialSecurityNumber { get; set; }
        public double SocialSecurityCurrentBalance { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cheque> Cheques { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contract> Contracts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerPayment> CustomerPayments { get; set; }
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeBranch> EmployeeBranches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeGivingCustody> EmployeeGivingCustodies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeReturnCashCustody> EmployeeReturnCashCustodies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeReturnCustody> EmployeeReturnCustodies { get; set; }
        public virtual Job Job { get; set; }
        public virtual Person Person { get; set; }
        public virtual SocialStatu SocialStatu { get; set; }
        public virtual Store Store { get; set; }
        public virtual Store Store1 { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Maintenance> Maintenances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Maintenance> Maintenances1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotificationEmployee> NotificationEmployees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionLineEmployee> ProductionLineEmployees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleMenCustomer> SaleMenCustomers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleMenStoreHistory> SaleMenStoreHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SellBackInvoice> SellBackInvoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SellInvoice> SellInvoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shift> Shifts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShiftsOffline> ShiftsOfflines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Store> Stores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Store> Stores1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StoresTransfer> StoresTransfers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StoresTransfer> StoresTransfers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VacationDay> VacationDays { get; set; }
    }
}
