//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Web.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maintenance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Maintenance()
        {
            this.ItemSerials = new HashSet<ItemSerial>();
            this.MaintenanceCaseHistories = new HashSet<MaintenanceCaseHistory>();
            this.MaintenanceDetails = new HashSet<MaintenanceDetail>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> StoreId { get; set; }
        public bool BySaleMen { get; set; }
        public Nullable<System.Guid> EmployeeSaleMenId { get; set; }
        public Nullable<System.Guid> EmployeeResponseId { get; set; }
        public Nullable<System.Guid> SellInvoiceId { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public Nullable<System.Guid> CustomerId { get; set; }
        public Nullable<System.Guid> BranchId { get; set; }
        public Nullable<int> PaymentTypeId { get; set; }
        public Nullable<System.Guid> SafeId { get; set; }
        public Nullable<System.Guid> BankAccountId { get; set; }
        public double DiscountPercentage { get; set; }
        public double InvoiceDiscount { get; set; }
        public double TotalDiscount { get; set; }
        public double TotalIncomes { get; set; }
        public double TotalSpareParts { get; set; }
        public double PayedValue { get; set; }
        public double RemindValue { get; set; }
        public double Safy { get; set; }
        public Nullable<int> MaintenanceCaseId { get; set; }
        public bool IsFinalApproval { get; set; }
        public bool HasCost { get; set; }
        public bool HasGuarantee { get; set; }
        public string Notes { get; set; }
        public bool IsApprovalAccountant { get; set; }
        public bool IsApprovalStore { get; set; }
        public Nullable<System.Guid> StoreReceiptId { get; set; }
        public Nullable<System.DateTime> ReceiptDate { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<System.Guid> DeletedBy { get; set; }
        public string InvoiceNumber { get; set; }
    
        public virtual BankAccount BankAccount { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemSerial> ItemSerials { get; set; }
        public virtual MaintenanceCa MaintenanceCa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaintenanceCaseHistory> MaintenanceCaseHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaintenanceDetail> MaintenanceDetails { get; set; }
        public virtual PaymentType PaymentType { get; set; }
        public virtual Person Person { get; set; }
        public virtual Safe Safe { get; set; }
        public virtual SellInvoice SellInvoice { get; set; }
        public virtual Store Store { get; set; }
        public virtual Store Store1 { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
    }
}
