//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Web.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseInvoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseInvoice()
        {
            this.CasesPurchaseInvoiceHistories = new HashSet<CasesPurchaseInvoiceHistory>();
            this.PurchaseBackInvoices = new HashSet<PurchaseBackInvoice>();
            this.PurchaseInvoicesDetails = new HashSet<PurchaseInvoicesDetail>();
            this.PurchaseInvoicesExpens = new HashSet<PurchaseInvoicesExpen>();
            this.SupplierPayments = new HashSet<SupplierPayment>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> SupplierId { get; set; }
        public Nullable<System.Guid> BranchId { get; set; }
        public Nullable<int> PaymentTypeId { get; set; }
        public Nullable<System.Guid> SafeId { get; set; }
        public Nullable<System.Guid> BankAccountId { get; set; }
        public Nullable<int> CaseId { get; set; }
        public Nullable<System.Guid> ShiftOfflineID { get; set; }
        public string InvoiceNumPaper { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public double TotalQuantity { get; set; }
        public double TotalValue { get; set; }
        public double TotalExpenses { get; set; }
        public double PayedValue { get; set; }
        public double RemindValue { get; set; }
        public double SalesTax { get; set; }
        public double ProfitTax { get; set; }
        public double InvoiceDiscount { get; set; }
        public double TotalDiscount { get; set; }
        public double Safy { get; set; }
        public bool IsApprovalAccountant { get; set; }
        public bool IsApprovalStore { get; set; }
        public bool IsFinalApproval { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> IsFullReturned { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<System.Guid> DeletedBy { get; set; }
        public string InvoiceNumber { get; set; }
        public double SalesTaxPercentage { get; set; }
        public double ProfitTaxPercentage { get; set; }
    
        public virtual BankAccount BankAccount { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual Case Case { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CasesPurchaseInvoiceHistory> CasesPurchaseInvoiceHistories { get; set; }
        public virtual PaymentType PaymentType { get; set; }
        public virtual Person Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseBackInvoice> PurchaseBackInvoices { get; set; }
        public virtual Safe Safe { get; set; }
        public virtual ShiftsOffline ShiftsOffline { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseInvoicesDetail> PurchaseInvoicesDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseInvoicesExpen> PurchaseInvoicesExpens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplierPayment> SupplierPayments { get; set; }
    }
}
