//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Web.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuoteOrderSell
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuoteOrderSell()
        {
            this.ProductionOrders = new HashSet<ProductionOrder>();
            this.QuoteOrderSellDetails = new HashSet<QuoteOrderSellDetail>();
            this.QuoteOrderSells1 = new HashSet<QuoteOrderSell>();
            this.SellInvoices = new HashSet<SellInvoice>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> CustomerId { get; set; }
        public Nullable<System.Guid> BranchId { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public double TotalQuantity { get; set; }
        public double TotalValue { get; set; }
        public string Notes { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<System.Guid> DeletedBy { get; set; }
        public int QuoteOrderSellType { get; set; }
        public Nullable<System.Guid> QuoteId { get; set; }
        public Nullable<int> OrderSellCaseId { get; set; }
        public double SalesTax { get; set; }
        public double SalesTaxPercentage { get; set; }
        public double ProfitTax { get; set; }
        public double ProfitTaxPercentage { get; set; }
        public double InvoiceDiscount { get; set; }
        public double DiscountPercentage { get; set; }
        public double Safy { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual OrderSellCas OrderSellCas { get; set; }
        public virtual Person Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionOrder> ProductionOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuoteOrderSellDetail> QuoteOrderSellDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuoteOrderSell> QuoteOrderSells1 { get; set; }
        public virtual QuoteOrderSell QuoteOrderSell1 { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SellInvoice> SellInvoices { get; set; }
    }
}
