//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Web.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class SellInvoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SellInvoice()
        {
            this.CasesSellInvoiceHistories = new HashSet<CasesSellInvoiceHistory>();
            this.CustomerPayments = new HashSet<CustomerPayment>();
            this.Installments = new HashSet<Installment>();
            this.ItemSerials = new HashSet<ItemSerial>();
            this.Maintenances = new HashSet<Maintenance>();
            this.OfferSellInvoices = new HashSet<OfferSellInvoice>();
            this.SellBackInvoices = new HashSet<SellBackInvoice>();
            this.SellInvoiceIncomes = new HashSet<SellInvoiceIncome>();
            this.SellInvoicePayments = new HashSet<SellInvoicePayment>();
            this.SellInvoicesDetails = new HashSet<SellInvoicesDetail>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> EmployeeId { get; set; }
        public Nullable<System.Guid> CustomerId { get; set; }
        public Nullable<System.Guid> BranchId { get; set; }
        public Nullable<int> PaymentTypeId { get; set; }
        public Nullable<System.Guid> SafeId { get; set; }
        public Nullable<System.Guid> BankAccountId { get; set; }
        public Nullable<System.Guid> ShiftOffLineID { get; set; }
        public Nullable<int> CaseId { get; set; }
        public bool BySaleMen { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public double TotalQuantity { get; set; }
        public double TotalValue { get; set; }
        public double TotalExpenses { get; set; }
        public double PayedValue { get; set; }
        public double RemindValue { get; set; }
        public double SalesTax { get; set; }
        public double ProfitTax { get; set; }
        public double InvoiceDiscount { get; set; }
        public double DiscountPercentage { get; set; }
        public double TotalDiscount { get; set; }
        public double Safy { get; set; }
        public bool IsApprovalAccountant { get; set; }
        public bool IsApprovalStore { get; set; }
        public bool IsFinalApproval { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> IsFullReturned { get; set; }
        public string InvoiceNumPaper { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<System.Guid> DeletedBy { get; set; }
        public string InvoiceNumber { get; set; }
        public double OffersDiscount { get; set; }
        public Nullable<System.Guid> OrderSellId { get; set; }
        public double SalesTaxPercentage { get; set; }
        public double ProfitTaxPercentage { get; set; }
    
        public virtual BankAccount BankAccount { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual Case Case { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CasesSellInvoiceHistory> CasesSellInvoiceHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerPayment> CustomerPayments { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Installment> Installments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemSerial> ItemSerials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Maintenance> Maintenances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfferSellInvoice> OfferSellInvoices { get; set; }
        public virtual PaymentType PaymentType { get; set; }
        public virtual Person Person { get; set; }
        public virtual QuoteOrderSell QuoteOrderSell { get; set; }
        public virtual Safe Safe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SellBackInvoice> SellBackInvoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SellInvoiceIncome> SellInvoiceIncomes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SellInvoicePayment> SellInvoicePayments { get; set; }
        public virtual ShiftsOffline ShiftsOffline { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SellInvoicesDetail> SellInvoicesDetails { get; set; }
    }
}
