BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.BankAccounts SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.Safes SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.Branches SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.PointOfSales
	(
	ID int NOT NULL IDENTITY (1, 1),
	Name nvarchar(MAX) NULL,
	BrunchId int NOT NULL,
	SafeID int NOT NULL,
	BankAccountID int NOT NULL,
	CreatedOn datetime NOT NULL,
	CreatedBy int NOT NULL,
	IsDeleted bit NOT NULL,
	DeletedOn datetime NULL,
	DeletedBy int NULL,
	LastModifiedOn datetime NULL,
	LastModifiedBy int NULL
	)  ON [PRIMARY]
	 TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE dbo.PointOfSales ADD CONSTRAINT
	PK_PointOfSales PRIMARY KEY CLUSTERED 
	(
	ID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.PointOfSales ADD CONSTRAINT
	FK_PointOfSales_Branches FOREIGN KEY
	(
	BrunchId
	) REFERENCES dbo.Branches
	(
	Id
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.PointOfSales ADD CONSTRAINT
	FK_PointOfSales_Safes FOREIGN KEY
	(
	SafeID
	) REFERENCES dbo.Safes
	(
	Id
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.PointOfSales ADD CONSTRAINT
	FK_PointOfSales_BankAccounts FOREIGN KEY
	(
	BankAccountID
	) REFERENCES dbo.BankAccounts
	(
	Id
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.PointOfSales SET (LOCK_ESCALATION = TABLE)
GO
COMMIT


BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.Users SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.PointOfSales ADD CONSTRAINT
	FK_PointOfSales_Users FOREIGN KEY
	(
	CreatedBy
	) REFERENCES dbo.Users
	(
	Id
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.PointOfSales ADD CONSTRAINT
	FK_PointOfSales_Users1 FOREIGN KEY
	(
	DeletedBy
	) REFERENCES dbo.Users
	(
	Id
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.PointOfSales ADD CONSTRAINT
	FK_PointOfSales_Users2 FOREIGN KEY
	(
	LastModifiedBy
	) REFERENCES dbo.Users
	(
	Id
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.PointOfSales SET (LOCK_ESCALATION = TABLE)
GO
COMMIT