BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.Employees SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.ShiftsOffline
	(
	ID int NOT NULL IDENTITY (1, 1),
	PointOfSaleID int NOT NULL,
	Date datetime NOT NULL,
	EmployeeID int NOT NULL,
	IsClosed bit NOT NULL,
	CreatedOn datetime NOT NULL,
	CreatedBy int NOT NULL,
	IsDelete bit NOT NULL,
	DeleteBy int NULL,
	DeletedOn datetime NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.ShiftsOffline ADD CONSTRAINT
	PK_ShiftsOffline PRIMARY KEY CLUSTERED 
	(
	ID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.ShiftsOffline ADD CONSTRAINT
	FK_ShiftsOffline_Employees FOREIGN KEY
	(
	EmployeeID
	) REFERENCES dbo.Employees
	(
	Id
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.ShiftsOffline SET (LOCK_ESCALATION = TABLE)
GO
COMMIT



BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.Users SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.PointOfSales SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.ShiftsOffline ADD CONSTRAINT
	FK_ShiftsOffline_PointOfSales FOREIGN KEY
	(
	PointOfSaleID
	) REFERENCES dbo.PointOfSales
	(
	ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.ShiftsOffline ADD CONSTRAINT
	FK_ShiftsOffline_Users FOREIGN KEY
	(
	CreatedBy
	) REFERENCES dbo.Users
	(
	Id
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.ShiftsOffline ADD CONSTRAINT
	FK_ShiftsOffline_Users1 FOREIGN KEY
	(
	DeleteBy
	) REFERENCES dbo.Users
	(
	Id
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.ShiftsOffline SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
