BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.ShiftsOffline SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.SellInvoices ADD
	ShiftOffLineID int NOT NULL CONSTRAINT DF_SellInvoices_ShiftID DEFAULT 1
GO
ALTER TABLE dbo.SellInvoices ADD CONSTRAINT
	FK_SellInvoices_ShiftsOffline FOREIGN KEY
	(
	ShiftOffLineID
	) REFERENCES dbo.ShiftsOffline
	(
	ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.SellInvoices SET (LOCK_ESCALATION = TABLE)
GO
COMMIT