BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.ShiftsOffline SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.PurchaseInvoices ADD
	ShiftOfflineID int NOT NULL CONSTRAINT DF_PurchaseInvoices_ShiftOfflineID DEFAULT 1
GO
ALTER TABLE dbo.PurchaseInvoices ADD CONSTRAINT
	FK_PurchaseInvoices_ShiftsOffline FOREIGN KEY
	(
	ShiftOfflineID
	) REFERENCES dbo.ShiftsOffline
	(
	ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.PurchaseInvoices SET (LOCK_ESCALATION = TABLE)
GO
COMMIT


BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.PurchaseInvoices
	DROP CONSTRAINT FK_PurchaseInvoices_ShiftsOffline
GO
ALTER TABLE dbo.ShiftsOffline SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.PurchaseInvoices
	DROP CONSTRAINT DF_PurchaseInvoices_ShiftOfflineID
GO
ALTER TABLE dbo.PurchaseInvoices ADD CONSTRAINT
	DF_PurchaseInvoices_ShiftOfflineID DEFAULT 1 FOR ShiftOfflineID
GO
ALTER TABLE dbo.PurchaseInvoices ADD CONSTRAINT
	FK_PurchaseInvoices_ShiftsOffline FOREIGN KEY
	(
	ShiftOfflineID
	) REFERENCES dbo.ShiftsOffline
	(
	ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.PurchaseInvoices SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.PurchaseBackInvoices ADD
	ShiftOfflineID int NOT NULL CONSTRAINT DF_PurchaseBackInvoices_ShiftOfflineID DEFAULT 1
GO
ALTER TABLE dbo.PurchaseBackInvoices ADD CONSTRAINT
	FK_PurchaseBackInvoices_ShiftsOffline FOREIGN KEY
	(
	ShiftOfflineID
	) REFERENCES dbo.ShiftsOffline
	(
	ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.PurchaseBackInvoices SET (LOCK_ESCALATION = TABLE)
GO
COMMIT