BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.PaymentTypes SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.Persons SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.PricingPolicies SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.PointOfSales ADD
	DefaultPricePolicyID int NULL,
	DefaultCustomerID int NULL,
	DefaultSupplierID int NULL,
	DefaultPaymentID int NULL,
	CanDiscount bit NOT NULL CONSTRAINT DF_PointOfSales_CanDiscount DEFAULT 0,
	CanChangePrice bit NOT NULL CONSTRAINT DF_PointOfSales_CanChangePrice DEFAULT 0
GO
ALTER TABLE dbo.PointOfSales ADD CONSTRAINT
	FK_PointOfSales_PricingPolicies FOREIGN KEY
	(
	DefaultPricePolicyID
	) REFERENCES dbo.PricingPolicies
	(
	Id
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.PointOfSales ADD CONSTRAINT
	FK_PointOfSales_Persons FOREIGN KEY
	(
	DefaultCustomerID
	) REFERENCES dbo.Persons
	(
	Id
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.PointOfSales ADD CONSTRAINT
	FK_PointOfSales_Persons1 FOREIGN KEY
	(
	DefaultSupplierID
	) REFERENCES dbo.Persons
	(
	Id
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.PointOfSales ADD CONSTRAINT
	FK_PointOfSales_PaymentTypes FOREIGN KEY
	(
	DefaultPaymentID
	) REFERENCES dbo.PaymentTypes
	(
	Id
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.PointOfSales SET (LOCK_ESCALATION = TABLE)
GO
COMMIT